"""add profile_picture and last_login

Revision ID: 30808ddea435
Revises: 
Create Date: 2026-06-06 11:50:43.089728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30808ddea435'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
