"""Update sentiment schema

Revision ID: 52d7f7f0089b
Revises: c2195e492669
Create Date: 2026-06-07 14:39:42.072427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d7f7f0089b'
down_revision = 'c2195e492669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Already applied in previous partial run
    # with op.batch_alter_table('search_history', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('overall_emotion', sa.String(length=64), nullable=True))
    #     batch_op.add_column(sa.Column('overall_risk_level', sa.String(length=32), nullable=True))
    #     batch_op.add_column(sa.Column('aggregated_sentiment_json', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('sentiment_analyzed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sentiment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dominant_emotion', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('model_version', sa.String(length=32), nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sentiment_label',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_sentiment_results_search_id'), ['search_id'], unique=False)
        batch_op.create_foreign_key('fk_sentiment_results_search_id', 'search_history', ['search_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentiment_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sentiment_results_search_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sentiment_results_search_id'))
        batch_op.alter_column('sentiment_label',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('model_version')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('confidence')
        batch_op.drop_column('dominant_emotion')
        batch_op.drop_column('search_id')

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_column('sentiment_analyzed_at')
        batch_op.drop_column('aggregated_sentiment_json')
        batch_op.drop_column('overall_risk_level')
        batch_op.drop_column('overall_emotion')

    # ### end Alembic commands ###
