"""add_search_and_article_m4_fields

Revision ID: c2195e492669
Revises: 30808ddea435
Create Date: 2026-06-07 09:54:35.844818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2195e492669'
down_revision = '30808ddea435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_search_id'), ['search_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_articles_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_articles_search_id', 'search_history', ['search_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fact_check_result', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('articles_collected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processing_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('search_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_column('search_status')
        batch_op.drop_column('processing_time')
        batch_op.drop_column('articles_collected')
        batch_op.drop_column('fact_check_result')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_articles_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_articles_search_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_user_id'))
        batch_op.drop_index(batch_op.f('ix_articles_search_id'))
        batch_op.drop_index(batch_op.f('ix_articles_content_hash'))
        batch_op.drop_column('content_hash')
        batch_op.drop_column('user_id')
        batch_op.drop_column('search_id')

    # ### end Alembic commands ###
